[package]
name = "wavelet-trie"
version = "0.1.0"
authors = ["Gerald Haesendonck <gerald.haesendonck@ugent.be>"]

[dependencies]
dyn-bit-vec = { git = 'https://github.com/ghsnd/dyn-bit-vec' }
#dyn-bit-vec = { path = '../dyn-bit-vec' }
